# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,1 4,15],
                [16,17,18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created


In [10]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size = (7,2))
random_array

array([[7, 7],
       [3, 6],
       [2, 4],
       [7, 1],
       [9, 2],
       [5, 5],
       [5, 0]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.5538672 , 0.00503041, 0.43379747, 0.95208981, 0.3785565 ],
       [0.55404557, 0.00927167, 0.89053991, 0.3171197 , 0.77945006],
       [0.20297285, 0.27389051, 0.41299685, 0.74636963, 0.63772247]])

In [31]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10,size = (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [46]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1,10, size = (3,7))
print(random_array)
# Find the unique numbers in the array you just created
np.unique(random_array)

[[1 9 9 1 7 8 9]
 [6 2 4 8 6 4 3]
 [8 8 5 8 3 8 5]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Find the 0'th index of the latest array you created
random_array[0]

array([1, 9, 9, 1, 7, 8, 9])

In [51]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[1, 9, 9, 1, 7, 8, 9],
       [6, 2, 4, 8, 6, 4, 3]])

In [53]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[1, 9],
       [6, 2]])

In [59]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr = np.random.randint(10, size = (3,5))
print(random_arr)
ones_arr = np.ones((3,5))
print(ones_arr)

[[9 6 4 5 4]
 [5 4 1 3 7]
 [0 5 0 6 5]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [63]:
# Add the two arrays together
addition = random_arr + ones_arr
addition

array([[10.,  7.,  5.,  6.,  5.],
       [ 6.,  5.,  2.,  4.,  8.],
       [ 1.,  6.,  1.,  7.,  6.]])

In [65]:
# Create another array of ones of shape (5, 3)
ones_arr2 = np.ones((5,3))
ones_arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
# Try add the array of ones and the other most recent array together
addtiton2 = ones_arr2 + random_arr
addtiton2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [67]:
# Create another array of ones of shape (3, 5)
ones_arr3 = np.ones((3,5))
ones_arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
# Subtract the new array of ones from the other most recent array
subtraction = random_arr - ones_arr3
subtraction

array([[ 8.,  5.,  3.,  4.,  3.],
       [ 4.,  3.,  0.,  2.,  6.],
       [-1.,  4., -1.,  5.,  4.]])

In [69]:
# Multiply the ones array with the latest array
multiplication = ones_arr3 * random_arr
multiplication

array([[9., 6., 4., 5., 4.],
       [5., 4., 1., 3., 7.],
       [0., 5., 0., 6., 5.]])

In [70]:
# Take the latest array to the power of 2 using '**'
random_arr ** 2

array([[81, 36, 16, 25, 16],
       [25, 16,  1,  9, 49],
       [ 0, 25,  0, 36, 25]])

In [71]:
# Do the same thing with np.square()
np.square(random_arr)

array([[81, 36, 16, 25, 16],
       [25, 16,  1,  9, 49],
       [ 0, 25,  0, 36, 25]])

In [72]:
# Find the mean of the latest array using np.mean()
np.mean(random_arr)

np.float64(4.266666666666667)

In [73]:
# Find the maximum of the latest array using np.max()
np.max(random_arr)

np.int64(9)

In [74]:
# Find the minimum of the latest array using np.min()
np.min(random_arr)

np.int64(0)

In [75]:
# Find the standard deviation of the latest array
np.std(random_arr)

np.float64(2.4073960113690385)

In [76]:
# Find the variance of the latest array
np.var(random_arr)

np.float64(5.795555555555556)

In [80]:
# Reshape the latest array to (3, 5, 1)
reshaped_arr = random_arr.reshape((3,5,1))
reshaped_arr

array([[[9],
        [6],
        [4],
        [5],
        [4]],

       [[5],
        [4],
        [1],
        [3],
        [7]],

       [[0],
        [5],
        [0],
        [6],
        [5]]])

In [ ]:
# Transpose the latest array: (3, 5, 1) -> (1, 5, 3)
transposed_arr = reshaped_arr.transpose()
transposed_arr

array([[[9, 5, 0],
        [6, 4, 5],
        [4, 1, 0],
        [5, 3, 6],
        [4, 7, 5]]])

What does the transpose do?

In [91]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(10, size = (3,3))
arr2 = np.random.randint(10, size = (3,2))
print("arr1: \n " , arr1)
print("arr2: \n " , arr2)

arr1: 
  [[7 5 6]
 [3 4 0]
 [7 4 0]]
arr2: 
  [[1 2]
 [7 8]
 [2 5]]


In [92]:
# Perform a dot product on the two newest arrays you created
prodct = np.dot(arr1 , arr2)
prodct

array([[54, 84],
       [31, 38],
       [35, 46]])

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(10, size = (4,3))
arr4 = np.random.randint(10, size = (4,3))


In [94]:
# Perform a dot product on the two newest arrays you created
product2 = np.dot(arr3 , arr4)
product2

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [95]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr4_t = arr4.transpose()
product2 = np.dot(arr3 , arr4_t)
product2

array([[ 64,  56,  48,  72],
       [ 91,  45,  62,  75],
       [ 28,   5,  57,  67],
       [135,  62, 121, 146]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [106]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_arr1 = np.random.randint(10, size = (2,3))
rand_arr2 = np.random.randint(10, size = (2,3))
print("rand_arr1: \n " , rand_arr1)
print("rand_arr2: \n " , rand_arr2)

rand_arr1: 
  [[1 1 3]
 [6 3 2]]
rand_arr2: 
  [[8 3 2]
 [8 6 8]]


In [107]:
# Compare the two arrays with '>'
comaprison = rand_arr1 > rand_arr2
comaprison

array([[False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [108]:
# Compare the two arrays with '>='
comparison2 = rand_arr1 >= rand_arr2
comparison2

array([[False, False,  True],
       [False, False, False]])

In [109]:
# Find which elements of the first array are greater than 7
comparison3 = rand_arr1 > 7
comparison3

array([[False, False, False],
       [False, False, False]])

In [110]:
# Which parts of each array are equal? (try using '==')
rand_arr1 == rand_arr2


array([[False, False, False],
       [False, False, False]])

In [111]:
# Sort one of the arrays you just created in ascending order
arr_sorted = np.sort(rand_arr2)
arr_sorted

array([[2, 3, 8],
       [6, 8, 8]])

In [112]:
# Sort the indexes of one of the arrays you just created
index_sorted = np.argsort(rand_arr2)
index_sorted

array([[2, 1, 0],
       [1, 0, 2]])

In [113]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_arr1)

np.int64(3)

In [116]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_arr1)

np.int64(0)

In [117]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_arr2, axis = 1)

array([0, 0])

In [118]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand_arr2, axis = 0)

array([0, 0, 0])

In [134]:
# Create an array of normally distributed random numbers
np.random.randn()

0.501458818094947

In [136]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.